// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data.proto

#include "data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_data_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_data_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_oIdentity;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_data_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_oValue;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_data_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_oAttribute;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_data_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_oUnit_AttresEntry_DoNotUse;
}  // namespace protobuf_data_2eproto
class oIdentityDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<oIdentity>
      _instance;
} _oIdentity_default_instance_;
class oValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<oValue>
      _instance;
} _oValue_default_instance_;
class oAttributeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<oAttribute>
      _instance;
} _oAttribute_default_instance_;
class oUnit_AttresEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<oUnit_AttresEntry_DoNotUse>
      _instance;
} _oUnit_AttresEntry_DoNotUse_default_instance_;
class oUnitDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<oUnit>
      _instance;
} _oUnit_default_instance_;
namespace protobuf_data_2eproto {
static void InitDefaultsoIdentity() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_oIdentity_default_instance_;
    new (ptr) ::oIdentity();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::oIdentity::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_oIdentity =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsoIdentity}, {}};

static void InitDefaultsoValue() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_oValue_default_instance_;
    new (ptr) ::oValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::oValue::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_oValue =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsoValue}, {}};

static void InitDefaultsoAttribute() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_oAttribute_default_instance_;
    new (ptr) ::oAttribute();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::oAttribute::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_oAttribute =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsoAttribute}, {
      &protobuf_data_2eproto::scc_info_oValue.base,}};

static void InitDefaultsoUnit_AttresEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_oUnit_AttresEntry_DoNotUse_default_instance_;
    new (ptr) ::oUnit_AttresEntry_DoNotUse();
  }
  ::oUnit_AttresEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_oUnit_AttresEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsoUnit_AttresEntry_DoNotUse}, {
      &protobuf_data_2eproto::scc_info_oAttribute.base,}};

static void InitDefaultsoUnit() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_oUnit_default_instance_;
    new (ptr) ::oUnit();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::oUnit::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_oUnit =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsoUnit}, {
      &protobuf_data_2eproto::scc_info_oIdentity.base,
      &protobuf_data_2eproto::scc_info_oUnit_AttresEntry_DoNotUse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_oIdentity.base);
  ::google::protobuf::internal::InitSCC(&scc_info_oValue.base);
  ::google::protobuf::internal::InitSCC(&scc_info_oAttribute.base);
  ::google::protobuf::internal::InitSCC(&scc_info_oUnit_AttresEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_oUnit.base);
}

::google::protobuf::Metadata file_level_metadata[5];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oIdentity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oIdentity, up_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oIdentity, down_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oValue, value_int_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oValue, value_float_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oValue, value_string_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oAttribute, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oAttribute, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oAttribute, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oAttribute, value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oUnit_AttresEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oUnit_AttresEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oUnit_AttresEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oUnit_AttresEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oUnit, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oUnit, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::oUnit, attres_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::oIdentity)},
  { 7, -1, sizeof(::oValue)},
  { 15, -1, sizeof(::oAttribute)},
  { 23, 30, sizeof(::oUnit_AttresEntry_DoNotUse)},
  { 32, -1, sizeof(::oUnit)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_oIdentity_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_oValue_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_oAttribute_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_oUnit_AttresEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_oUnit_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "data.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

static void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ndata.proto\"%\n\toIdentity\022\n\n\002up\030\001 \001(\005\022\014\n"
      "\004down\030\002 \001(\005\"F\n\006oValue\022\021\n\tvalue_int\030\001 \001(\003"
      "\022\023\n\013value_float\030\002 \001(\002\022\024\n\014value_string\030\003 "
      "\001(\t\"H\n\noAttribute\022\014\n\004name\030\001 \001(\t\022\024\n\004type\030"
      "\002 \001(\0162\006.eType\022\026\n\005value\030\003 \001(\0132\007.oValue\"\177\n"
      "\005oUnit\022\026\n\002id\030\001 \001(\0132\n.oIdentity\022\"\n\006attres"
      "\030\002 \003(\0132\022.oUnit.AttresEntry\032:\n\013AttresEntr"
      "y\022\013\n\003key\030\001 \001(\t\022\032\n\005value\030\002 \001(\0132\013.oAttribu"
      "te:\0028\001*-\n\005eUnit\022\n\n\006player\020\000\022\014\n\010hercules\020"
      "\001\022\n\n\006buffer\020\002*-\n\005eType\022\t\n\005__int\020\000\022\013\n\007__f"
      "loat\020\001\022\014\n\010__string\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 428);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "data.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_data_2eproto
const ::google::protobuf::EnumDescriptor* eUnit_descriptor() {
  protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_data_2eproto::file_level_enum_descriptors[0];
}
bool eUnit_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* eType_descriptor() {
  protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_data_2eproto::file_level_enum_descriptors[1];
}
bool eType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void oIdentity::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int oIdentity::kUpFieldNumber;
const int oIdentity::kDownFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

oIdentity::oIdentity()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_data_2eproto::scc_info_oIdentity.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:oIdentity)
}
oIdentity::oIdentity(const oIdentity& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&up_, &from.up_,
    static_cast<size_t>(reinterpret_cast<char*>(&down_) -
    reinterpret_cast<char*>(&up_)) + sizeof(down_));
  // @@protoc_insertion_point(copy_constructor:oIdentity)
}

void oIdentity::SharedCtor() {
  ::memset(&up_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&down_) -
      reinterpret_cast<char*>(&up_)) + sizeof(down_));
}

oIdentity::~oIdentity() {
  // @@protoc_insertion_point(destructor:oIdentity)
  SharedDtor();
}

void oIdentity::SharedDtor() {
}

void oIdentity::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* oIdentity::descriptor() {
  ::protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const oIdentity& oIdentity::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_data_2eproto::scc_info_oIdentity.base);
  return *internal_default_instance();
}


void oIdentity::Clear() {
// @@protoc_insertion_point(message_clear_start:oIdentity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&up_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&down_) -
      reinterpret_cast<char*>(&up_)) + sizeof(down_));
  _internal_metadata_.Clear();
}

bool oIdentity::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:oIdentity)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 up = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &up_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 down = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &down_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:oIdentity)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:oIdentity)
  return false;
#undef DO_
}

void oIdentity::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:oIdentity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 up = 1;
  if (this->up() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->up(), output);
  }

  // int32 down = 2;
  if (this->down() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->down(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:oIdentity)
}

::google::protobuf::uint8* oIdentity::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:oIdentity)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 up = 1;
  if (this->up() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->up(), target);
  }

  // int32 down = 2;
  if (this->down() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->down(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oIdentity)
  return target;
}

size_t oIdentity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oIdentity)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 up = 1;
  if (this->up() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->up());
  }

  // int32 down = 2;
  if (this->down() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->down());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void oIdentity::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:oIdentity)
  GOOGLE_DCHECK_NE(&from, this);
  const oIdentity* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const oIdentity>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:oIdentity)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:oIdentity)
    MergeFrom(*source);
  }
}

void oIdentity::MergeFrom(const oIdentity& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:oIdentity)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.up() != 0) {
    set_up(from.up());
  }
  if (from.down() != 0) {
    set_down(from.down());
  }
}

void oIdentity::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:oIdentity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void oIdentity::CopyFrom(const oIdentity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oIdentity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool oIdentity::IsInitialized() const {
  return true;
}

void oIdentity::Swap(oIdentity* other) {
  if (other == this) return;
  InternalSwap(other);
}
void oIdentity::InternalSwap(oIdentity* other) {
  using std::swap;
  swap(up_, other->up_);
  swap(down_, other->down_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata oIdentity::GetMetadata() const {
  protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void oValue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int oValue::kValueIntFieldNumber;
const int oValue::kValueFloatFieldNumber;
const int oValue::kValueStringFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

oValue::oValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_data_2eproto::scc_info_oValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:oValue)
}
oValue::oValue(const oValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value_string().size() > 0) {
    value_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_string_);
  }
  ::memcpy(&value_int_, &from.value_int_,
    static_cast<size_t>(reinterpret_cast<char*>(&value_float_) -
    reinterpret_cast<char*>(&value_int_)) + sizeof(value_float_));
  // @@protoc_insertion_point(copy_constructor:oValue)
}

void oValue::SharedCtor() {
  value_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&value_int_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_float_) -
      reinterpret_cast<char*>(&value_int_)) + sizeof(value_float_));
}

oValue::~oValue() {
  // @@protoc_insertion_point(destructor:oValue)
  SharedDtor();
}

void oValue::SharedDtor() {
  value_string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void oValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* oValue::descriptor() {
  ::protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const oValue& oValue::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_data_2eproto::scc_info_oValue.base);
  return *internal_default_instance();
}


void oValue::Clear() {
// @@protoc_insertion_point(message_clear_start:oValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_string_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&value_int_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_float_) -
      reinterpret_cast<char*>(&value_int_)) + sizeof(value_float_));
  _internal_metadata_.Clear();
}

bool oValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:oValue)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 value_int = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &value_int_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float value_float = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &value_float_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value_string = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value_string()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value_string().data(), static_cast<int>(this->value_string().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "oValue.value_string"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:oValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:oValue)
  return false;
#undef DO_
}

void oValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:oValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 value_int = 1;
  if (this->value_int() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->value_int(), output);
  }

  // float value_float = 2;
  if (this->value_float() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->value_float(), output);
  }

  // string value_string = 3;
  if (this->value_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value_string().data(), static_cast<int>(this->value_string().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "oValue.value_string");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->value_string(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:oValue)
}

::google::protobuf::uint8* oValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:oValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 value_int = 1;
  if (this->value_int() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->value_int(), target);
  }

  // float value_float = 2;
  if (this->value_float() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->value_float(), target);
  }

  // string value_string = 3;
  if (this->value_string().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value_string().data(), static_cast<int>(this->value_string().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "oValue.value_string");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->value_string(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oValue)
  return target;
}

size_t oValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oValue)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string value_string = 3;
  if (this->value_string().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value_string());
  }

  // int64 value_int = 1;
  if (this->value_int() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->value_int());
  }

  // float value_float = 2;
  if (this->value_float() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void oValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:oValue)
  GOOGLE_DCHECK_NE(&from, this);
  const oValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const oValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:oValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:oValue)
    MergeFrom(*source);
  }
}

void oValue::MergeFrom(const oValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:oValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value_string().size() > 0) {

    value_string_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_string_);
  }
  if (from.value_int() != 0) {
    set_value_int(from.value_int());
  }
  if (from.value_float() != 0) {
    set_value_float(from.value_float());
  }
}

void oValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:oValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void oValue::CopyFrom(const oValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool oValue::IsInitialized() const {
  return true;
}

void oValue::Swap(oValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void oValue::InternalSwap(oValue* other) {
  using std::swap;
  value_string_.Swap(&other->value_string_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(value_int_, other->value_int_);
  swap(value_float_, other->value_float_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata oValue::GetMetadata() const {
  protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void oAttribute::InitAsDefaultInstance() {
  ::_oAttribute_default_instance_._instance.get_mutable()->value_ = const_cast< ::oValue*>(
      ::oValue::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int oAttribute::kNameFieldNumber;
const int oAttribute::kTypeFieldNumber;
const int oAttribute::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

oAttribute::oAttribute()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_data_2eproto::scc_info_oAttribute.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:oAttribute)
}
oAttribute::oAttribute(const oAttribute& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_value()) {
    value_ = new ::oValue(*from.value_);
  } else {
    value_ = NULL;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:oAttribute)
}

void oAttribute::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&value_)) + sizeof(type_));
}

oAttribute::~oAttribute() {
  // @@protoc_insertion_point(destructor:oAttribute)
  SharedDtor();
}

void oAttribute::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete value_;
}

void oAttribute::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* oAttribute::descriptor() {
  ::protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const oAttribute& oAttribute::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_data_2eproto::scc_info_oAttribute.base);
  return *internal_default_instance();
}


void oAttribute::Clear() {
// @@protoc_insertion_point(message_clear_start:oAttribute)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && value_ != NULL) {
    delete value_;
  }
  value_ = NULL;
  type_ = 0;
  _internal_metadata_.Clear();
}

bool oAttribute::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:oAttribute)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "oAttribute.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .eType type = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::eType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .oValue value = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:oAttribute)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:oAttribute)
  return false;
#undef DO_
}

void oAttribute::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:oAttribute)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "oAttribute.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // .eType type = 2;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->type(), output);
  }

  // .oValue value = 3;
  if (this->has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:oAttribute)
}

::google::protobuf::uint8* oAttribute::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:oAttribute)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "oAttribute.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // .eType type = 2;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->type(), target);
  }

  // .oValue value = 3;
  if (this->has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_value(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oAttribute)
  return target;
}

size_t oAttribute::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oAttribute)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // .oValue value = 3;
  if (this->has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *value_);
  }

  // .eType type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void oAttribute::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:oAttribute)
  GOOGLE_DCHECK_NE(&from, this);
  const oAttribute* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const oAttribute>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:oAttribute)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:oAttribute)
    MergeFrom(*source);
  }
}

void oAttribute::MergeFrom(const oAttribute& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:oAttribute)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_value()) {
    mutable_value()->::oValue::MergeFrom(from.value());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void oAttribute::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:oAttribute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void oAttribute::CopyFrom(const oAttribute& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oAttribute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool oAttribute::IsInitialized() const {
  return true;
}

void oAttribute::Swap(oAttribute* other) {
  if (other == this) return;
  InternalSwap(other);
}
void oAttribute::InternalSwap(oAttribute* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(value_, other->value_);
  swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata oAttribute::GetMetadata() const {
  protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

oUnit_AttresEntry_DoNotUse::oUnit_AttresEntry_DoNotUse() {}
oUnit_AttresEntry_DoNotUse::oUnit_AttresEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void oUnit_AttresEntry_DoNotUse::MergeFrom(const oUnit_AttresEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata oUnit_AttresEntry_DoNotUse::GetMetadata() const {
  ::protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[3];
}
void oUnit_AttresEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void oUnit::InitAsDefaultInstance() {
  ::_oUnit_default_instance_._instance.get_mutable()->id_ = const_cast< ::oIdentity*>(
      ::oIdentity::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int oUnit::kIdFieldNumber;
const int oUnit::kAttresFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

oUnit::oUnit()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_data_2eproto::scc_info_oUnit.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:oUnit)
}
oUnit::oUnit(const oUnit& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  attres_.MergeFrom(from.attres_);
  if (from.has_id()) {
    id_ = new ::oIdentity(*from.id_);
  } else {
    id_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:oUnit)
}

void oUnit::SharedCtor() {
  id_ = NULL;
}

oUnit::~oUnit() {
  // @@protoc_insertion_point(destructor:oUnit)
  SharedDtor();
}

void oUnit::SharedDtor() {
  if (this != internal_default_instance()) delete id_;
}

void oUnit::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* oUnit::descriptor() {
  ::protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const oUnit& oUnit::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_data_2eproto::scc_info_oUnit.base);
  return *internal_default_instance();
}


void oUnit::Clear() {
// @@protoc_insertion_point(message_clear_start:oUnit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  attres_.Clear();
  if (GetArenaNoVirtual() == NULL && id_ != NULL) {
    delete id_;
  }
  id_ = NULL;
  _internal_metadata_.Clear();
}

bool oUnit::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:oUnit)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .oIdentity id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_id()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, .oAttribute> attres = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          oUnit_AttresEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              oUnit_AttresEntry_DoNotUse,
              ::std::string, ::oAttribute,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::std::string, ::oAttribute > > parser(&attres_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "oUnit.AttresEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:oUnit)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:oUnit)
  return false;
#undef DO_
}

void oUnit::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:oUnit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .oIdentity id = 1;
  if (this->has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_id(), output);
  }

  // map<string, .oAttribute> attres = 2;
  if (!this->attres().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::oAttribute >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "oUnit.AttresEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->attres().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->attres().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::oAttribute >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::oAttribute >::const_iterator
          it = this->attres().begin();
          it != this->attres().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<oUnit_AttresEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(attres_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<oUnit_AttresEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::oAttribute >::const_iterator
          it = this->attres().begin();
          it != this->attres().end(); ++it) {
        entry.reset(attres_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:oUnit)
}

::google::protobuf::uint8* oUnit::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:oUnit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .oIdentity id = 1;
  if (this->has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_id(), deterministic, target);
  }

  // map<string, .oAttribute> attres = 2;
  if (!this->attres().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::oAttribute >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "oUnit.AttresEntry.key");
      }
    };

    if (deterministic &&
        this->attres().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->attres().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::oAttribute >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::oAttribute >::const_iterator
          it = this->attres().begin();
          it != this->attres().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<oUnit_AttresEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(attres_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<oUnit_AttresEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::oAttribute >::const_iterator
          it = this->attres().begin();
          it != this->attres().end(); ++it) {
        entry.reset(attres_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oUnit)
  return target;
}

size_t oUnit::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oUnit)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, .oAttribute> attres = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->attres_size());
  {
    ::std::unique_ptr<oUnit_AttresEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::oAttribute >::const_iterator
        it = this->attres().begin();
        it != this->attres().end(); ++it) {
      entry.reset(attres_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // .oIdentity id = 1;
  if (this->has_id()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *id_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void oUnit::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:oUnit)
  GOOGLE_DCHECK_NE(&from, this);
  const oUnit* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const oUnit>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:oUnit)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:oUnit)
    MergeFrom(*source);
  }
}

void oUnit::MergeFrom(const oUnit& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:oUnit)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  attres_.MergeFrom(from.attres_);
  if (from.has_id()) {
    mutable_id()->::oIdentity::MergeFrom(from.id());
  }
}

void oUnit::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:oUnit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void oUnit::CopyFrom(const oUnit& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oUnit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool oUnit::IsInitialized() const {
  return true;
}

void oUnit::Swap(oUnit* other) {
  if (other == this) return;
  InternalSwap(other);
}
void oUnit::InternalSwap(oUnit* other) {
  using std::swap;
  attres_.Swap(&other->attres_);
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata oUnit::GetMetadata() const {
  protobuf_data_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_data_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::oIdentity* Arena::CreateMaybeMessage< ::oIdentity >(Arena* arena) {
  return Arena::CreateInternal< ::oIdentity >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::oValue* Arena::CreateMaybeMessage< ::oValue >(Arena* arena) {
  return Arena::CreateInternal< ::oValue >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::oAttribute* Arena::CreateMaybeMessage< ::oAttribute >(Arena* arena) {
  return Arena::CreateInternal< ::oAttribute >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::oUnit_AttresEntry_DoNotUse* Arena::CreateMaybeMessage< ::oUnit_AttresEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::oUnit_AttresEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::oUnit* Arena::CreateMaybeMessage< ::oUnit >(Arena* arena) {
  return Arena::CreateInternal< ::oUnit >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
